# Cloud Build configuration for ContinuonAI Backend API
# Builds and deploys to Cloud Run

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/continuonai-api:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/continuonai-api:latest'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/continuonai-api:latest'
      - '.'
    id: 'build'

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/continuonai-api:$COMMIT_SHA'
    id: 'push-sha'
    waitFor: ['build']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/continuonai-api:latest'
    id: 'push-latest'
    waitFor: ['build']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'continuonai-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/continuonai-api:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
    id: 'deploy'
    waitFor: ['push-sha']

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Substitutions (can be overridden)
substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'continuonai-api'

# Build timeout
timeout: '1200s'

# Images to store
images:
  - 'gcr.io/$PROJECT_ID/continuonai-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/continuonai-api:latest'
