// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsj-t_t2DiITiesmzzUJ9pQr-OycmjH3Y',
    appId: '1:252875087112:web:f76b9ea08d6bc992c120bd',
    messagingSenderId: '252875087112',
    projectId: 'continuonai',
    authDomain: 'continuonai.firebaseapp.com',
    storageBucket: 'continuonai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWah7U7wicLlojMNOhYjj8s8A2WldPFyw',
    appId: '1:252875087112:android:49044c6a031233d6c120bd',
    messagingSenderId: '252875087112',
    projectId: 'continuonai',
    storageBucket: 'continuonai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzQ2mvb0-KpaYtChTS3Qjy8jJkNjVB0W8',
    appId: '1:252875087112:ios:9f7be47bf14a1bdec120bd',
    messagingSenderId: '252875087112',
    projectId: 'continuonai',
    storageBucket: 'continuonai.firebasestorage.app',
    iosBundleId: 'com.continuonxr.fluttercompanion.flutterCompanion',
  );

}